config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/contact'

  get 'static_pages/about'

  get 'admin' => 'admin#index'

match '/contacts',     to: 'contacts#new',             via: 'get'
resources "contacts", only: [:new, :create]

  resources :users
  resources :orders
  resources :line_items
  resources :carts
  get 'store/index'
  get 'store/show'

  resources :products
  resources :products

  resources :products do
  get :who_bought, :on => :member
  end
  

  root :to => 'store#index', :as => 'store' 

  controller :sessions do
  get 'login' => :new
  post 'login' => :create
  delete 'logout' => :destroy
  end

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
	belongs_to :order
	belongs_to :product
	belongs_to :cart


	def total_price
		product.price * quantity
    end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
skip_before_filter :authorize, :only => [:create, :update]  
  # GET /line_items
  # GET /line_items.xml
  def index
    @cart = current_cart

    @line_items = LineItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @line_items }
    end
  end

  # GET /line_items/1
  # GET /line_items/1.xml
  def show
    @cart = current_cart

    @line_item = LineItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @line_item }
    end
  end

  # GET /line_items/new
  # GET /line_items/new.xml
  def new
    @line_item = LineItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @line_item }
    end
  end

  # GET /line_items/1/edit
  def edit
    @cart = current_cart
    @line_item = LineItem.find(params[:id])
  end

  # POST /line_items
  # POST /line_items.xml
  def create
    @cart = current_cart
    product = Product.find(params[:product_id])
    #order = Order.find(order_params)
    @line_item = @cart.add_product(product.id)

    respond_to do |format|
      if @line_item.save        
        format.html { redirect_to(store_url) } 
             
        format.js   { @current_item = @line_item }
        #format.json { render action: 'show', status: :created, location: @line_item }
        
        format.xml  { render :xml => @line_item,
         :status => :created, :location => @line_item }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @line_item.errors,
          :status => :unprocessable_entity }
      end
    end
  end

  # PUT /line_items/1
  # PUT /line_items/1.xml
  def update
    
    @cart = current_cart.id
    product = (params[:id])
    @line_item = LineItem.where({:product_id => product, :cart_id => @cart}).last
    @quantity = @line_item[:quantity]
    @quantity -= 1
    @quantity
    @line_items_quantity = LineItem.select(:quantity).where({:cart_id => @cart})    

    respond_to do |format|
      if (@line_item.update_attributes(:quantity => @quantity))&&(@quantity > 0) #@line_item.update_attributes(params[:line_item])
        format.html { redirect_to(store_url, :notice => 'Line item was successfully updated.') }
        
        format.js   #{ @current_item = @line_item }
        format.json #{ render action: 'show', status: :created, location: @line_item }
        #format.json { render action: 'show', status: :created, location: @line_item }
        format.xml  { head :ok }
      else
         @line_item.destroy

      if @line_items_quantity.empty?
         format.js {render inline: "location.reload();" }
       else      
      format.js 

        #format.html { redirect_to(store_url)}
        #format.html { render :action => "delete" } #format.html { render :action => "edit" }
        #format.xml  { render :xml => @line_item.errors, :status => :unprocessable_entity }
                
      end         
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.xml
  def destroy
    
    @cart = current_cart.id
    product = (params[:id])

    @line_item = LineItem.where({:product_id => product, :cart_id => @cart}) #POZIVANJE IZ TABELE SA USLOVOM
    
    @line_item    

    @line_item.destroy(@line_item)

    respond_to do |format|
      format.html { redirect_to (store_url) } #vraca na trenutnu korpu kupca
      format.xml  { head :ok }
    end
  end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.number_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :cart_id %><br>
    <%= f.number_field :cart_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<% if line_item == @current_item %>

<tr id="current_item">
<% else %>
<tr >
<% end %>
<td class="line_item"> <%= line_item.quantity %>&times; </td>
<td class="line_item"> <%= line_item.product.title %> </td>
 <td class="line_item"><%= sprintf("din %0.02f", line_item.total_price) %> &nbsp; </td> <!-- <%= number_to_currency(line_item.total_price) %> -->

 <% if @order.nil? %>
 <td style="color:black"><%= button_to '-', line_item_path(line_item.product.id), method: 'put',
  :remote => true %></td> <!-- SMANJUJE KOLICINU ZA 1 -->
  <% end %>

  
 </tr>
 </tr>

app/views/line_items/_line_item.text.erb
<%= sprintf("%2d x %s" , line_item.quantity, truncate(line_item.product.title, :length => 50)) %>

app/views/line_items/create.js.erb
$("#notice").hide();

if ($('#cart tr').length == 1) { $('#cart').show('blind', 1000); }

$('#cart').html("<%= escape_javascript render(@cart) %>");

$("#current_item").css({'background-color':"white"})
.animate({'background-color':"#0D0000"}, 1000);

app/views/line_items/edit.html.erb
<h1>Editing Line Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Line Items</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.product_id %></td>
        <td><%= line_item.cart_id %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New Line Item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @line_item.product_id %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @line_item.cart_id %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/update.js.erb
$('#cart').html("<%= escape_javascript render(@line_item.cart) %>");