config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/contact'

  get 'static_pages/about'

  get 'admin' => 'admin#index'

match '/contacts',     to: 'contacts#new',             via: 'get'
resources "contacts", only: [:new, :create]

  resources :users
  resources :orders
  resources :line_items
  resources :carts
  get 'store/index'
  get 'store/show'

  resources :products
  resources :products

  resources :products do
  get :who_bought, :on => :member
  end
  

  root :to => 'store#index', :as => 'store' 

  controller :sessions do
  get 'login' => :new
  post 'login' => :create
  delete 'logout' => :destroy
  end

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, dependent: :destroy

	def total_price
		line_items.to_a.sum { |item| item.total_price }
    end

	def add_product(product_id)
		current_item = line_items.where(:product_id => product_id).first

		if current_item
			current_item.quantity += 1			
		else
			current_item = line_items.build(:product_id => product_id)			
		end
		current_item
	end
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Poruka sa sajta Bacva.rs",
      :to => "bacvashop@gmail.com",                            #"your_email@example.org",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
	belongs_to :order
	belongs_to :product
	belongs_to :cart


	def total_price
		product.price * quantity
    end
end

app/models/order.rb
class Order < ActiveRecord::Base
	has_many :line_items, :dependent => :destroy


	PAYMENT_TYPES = [ "Gotovinsko placanje" , "Virmansko" , "Online placanje" ]



def add_line_items_from_cart(cart)
	cart.line_items.each do |item|
		item.cart_id = nil
		line_items << item
	end
end

def total_price
		line_items.to_a.sum { |item| item.total_price }
end





	validates :name, :address, :email, :pay_type, :presence => true
	validates :pay_type, :inclusion => PAYMENT_TYPES
end

app/models/product.rb
class Product < ActiveRecord::Base

mount_uploader :picture, PictureUploader						 

	default_scope { order(created_at: :desc) }
	has_many :line_items
	has_many :orders, :through => :line_items

	validates :title, :description, :type_of_wine, :presence => true # :image_url
	validates :price, :numericality => {:greater_than_or_equal_to => 0.01} 
	validates :title, :uniqueness => true
	#validates :image_url, :format => {
	#:with => %r{\.(gif|jpg|png)\z}i,
    #:message => 'must be a URL for GIF, JPG or PNG image.'
	#}

before_destroy :ensure_not_referenced_by_any_line_item

def ensure_not_referenced_by_any_line_item

	if line_items.count.zero?
		return true
	else
		errors.add(:base, 'Line Items present')
	return false
	
	end
	end

	# It returns the articles whose titles contain one or more words that form the query
  def self.search(query)
    # where(:title, query) -> This would return an exact match of the query
    where("title like ?", "%#{query}%") 
  end


end

app/models/user.rb
require 'digest/sha2'
class User < ActiveRecord::Base

	validates :name, :presence => true, :uniqueness => true
 
  validates :password, :confirmation => true
  attr_accessor :password_confirmation
  attr_reader   :password

  validate  :password_must_be_present
  
  def User.authenticate(name, password)
    if user = find_by_name(name)
      if user.hashed_password == encrypt_password(password, user.salt)
        user
      end
    end
  end

  def User.encrypt_password(password, salt)
    Digest::SHA2.hexdigest(password + "wibble" + salt)
  end
  
  # 'password' is a virtual attribute
  def password=(password)
    @password = password

    if password.present?
      generate_salt
      self.hashed_password = self.class.encrypt_password(password, salt)
    end
  end
  
  private

    def password_must_be_present
      errors.add(:password, "Missing password") unless hashed_password.present?
    end
  
    def generate_salt
      self.salt = self.object_id.to_s + rand.to_s
    end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  #include CurrentCart
  def index
  	@cart = current_cart  	
  	@total_orders = Order.count
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_filter :authorize, :only => [:create, :update, :destroy]
  
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show 
  begin
    @cart = Cart.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    logger.error "Invalid cart #{ params[:id] }"
    redirect_to store_url, :notice =>'Pokusavate da pristupite nepostojecoj korpi'
  else
    respond_to do |format|
      format.html # show.html.erb 
      format.json { render json: @cart }

  end
end
end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
   #@cart = Cart.find(params[:id])
  end
  
  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = current_cart
    @cart.destroy
    session[:cart_id] = nil

    respond_to do |format|
      format.html { redirect_to store_url, notice: 'Vasa Korpa je trenutno prazna.' }
      format.js
      #format.json { head :ok }
      format.json { render action: 'show', status: :created, location: @cart }
    end
  end

  private
   
    # Use callbacks to share common setup or constraints between actions.
   def set_cart      
    if Cart == nil
      return show
    elsif @cart != nil
      @cart = Cart.find(params[:id])
   end
    
   end    

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
    params[:cart]
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def hidden_div_if(condition, attributes = {}, &block)
		if condition
			attributes["style" ] = "display: none"
		end
		content_tag("div" , attributes, &block)
	end
end

app/helpers/carts_helper.rb
module CartsHelper
	
end

app/helpers/contact_form_helper.rb
module ContactFormHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper

	
	
end

app/helpers/pageoverride.rb
module Pageoverride
  class PaginationListLinkRenderer < WillPaginate::ActionView::LinkRenderer
     def prepare(collection, options, template)
    @gap_marker = options.delete(:gap)
    super
  end
  
  def visible_page_numbers
    inner_window, outer_window = @options[:inner_window].to_i, @options[:outer_window].to_i
    window_from = current_page - inner_window
    window_to = current_page + inner_window
    
    # adjust lower or upper limit if other is out of bounds
    if window_to > total_pages
      window_from -= window_to - total_pages
      window_to = total_pages
    end
    if window_from < 1
      window_to += 1 - window_from
      window_from = 1
      window_to = total_pages if window_to > total_pages
    end
    
    visible = (1..total_pages).to_a #start with all of them...
    
    left_gap = right_gap = (2 + outer_window)...(total_pages - outer_window)
    visible -= left_gap.to_a if left_gap.last - left_gap.first > 1
    visible -= right_gap.to_a if right_gap.last - right_gap.first > 1

    visible
  end
end
  end

app/helpers/products_helper.rb
module ProductsHelper



end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1>Dobrodosli</h1>
<h3> Datum i vreme <%= Time.now %> </h3>
<h3>Trenutan broj porudzbina je <%= @total_orders %>.</h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>


  <title>Bacva</title>
 
 <%= stylesheet_link_tag "application" %>
 
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
   
  <%= csrf_meta_tags %>
</head>
<body>    		

	<div class="container">
		<div class="jumbotron">
					 
		</div>
		</div>

<div class="navbar navbar-default navbar-fixed-top" id="meni">
<div class="container-fluid">
<div class="navbar-header">
<button type="button" class="navbar-toggle collapsed" datatoggle="
collapse" data-target="#collapibleMenu">
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
<a href="<%= store_path %>" class="navbar-brand">OnlineBacvaShop</a>
</div>
<div class="collapse navbar-collapse" id="collapibleMenu">
<ul class="nav navbar-nav navbar-right">

				
				<li><a href="<%= store_path %>">Pocetna</a></li>
				
				<li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Napredna pretraga</a>

				<ul class="dropdown-menu" role="menu">
				<li class="dropdown-submenu"><a  href="#">Pretraga po vrstama</a>
				<ul class="dropdown-menu" role="menu">
		              <li><a href="<%= store_path(:type_of_wine => 'Crveno vino') %>">Crvena vina</a></li>
		              <li><a href="<%= store_path(:type_of_wine => 'Belo vino') %>">Bela vina</a></li>
		              <li><a href="<%= store_path(:type_of_wine => 'Ruzicasto vino') %>">Ruzicasta vina</a></li>
		        </li>
		        </ul>
		              <li class="dropdown-submenu"><a  href="#">Pretraga po cenama</a>
    					<ul class="dropdown-menu">      						
      						<li><a tabindex="-1" href=" <%= store_path(price: '1') %>">100 - 200 din</a></li>
      						<li><a href=" <%= store_path(price: '2') %>">200 - 300 din</a></li>
      						<li><a href=" <%= store_path(price: '3') %>">300 - 500 din</a></li>      
    					</ul>
  					  </li>
  				</ul>		

				<li><a href="<%= contacts_path %>">Kontakt</a></li>
				<li><a href="<%= static_pages_about_path %>">O nama</a></li>
				<li><a href="<%= admin_path %>">Ulaz za Administratora</a></li>	
			
</ul>

</div>
</div>
</div>



	
<div id = "container" id="centriraj_kontejner">
	<div class="row" id="centriraj_red">
		<div class="col-xs-12 col-sm-4 col-md-4 col-lg-3 text-center" id="leva_kolona" >

				<div id="search">

				 <%= form_tag(store_path, :method => "get") do %>

				<%= text_field_tag :search, params[:search], class: "span2", placeholder: "Pretrazi proizvode" %>

				<%= button_to 'Pretrazi' %>
				<% end %>

				</div>
				<div class="sidebar">
					<img src="/images/wineglass.png" class="img-responsive" alt="glass">
					</div>
				</div>
			
			
			<div class="col-xs-12 col-sm-4 col-md-4 col-lg-6 text-center" id="centar">
				
				
					<%= yield %>
					
				
				</div>			
				
				

			<div class="col-xs-12 col-sm-4 col-md-4 col-lg-3 text-center" id="desna_kolona">

				
					<div id = "cart">
						<%= hidden_div_if(@cart.line_items.empty?, id: "cart" ) do %>
							<%= render @cart %>
						<% end %>
					</div>

					<div id="admin_panel">
					
					<% if session[:user_id] %>
					<br />
					<%= link_to 'Porudzbine' , orders_path, :class=>"btn btn-primary" %><br />
					<br />
					<%= link_to 'Proizvodi' , products_path, :class=>"btn btn-primary" %><br />
					<br />
					<%= button_to 'Izadji' , logout_path, :class=>"btn btn-warning", :method => :delete %>
					<% else %>
					<div id="reklama2">
					<p style="font-style:italic; font-size:18px; color:green">Vaš sadržaj korpe u svakom trenutku možete izmeniti dodavanjem novih proizvoda ili brisanjem već dodatih. Proizvodi se isporučuju na vašu adresu uslugom brze pošte u originalnoj ambalaži.</p>


					</div>
					<% end %>

					<div id="bure">
					<img src="/bure.png">
					</div>
										
					</div>
				</div>
			</div>
</div>


<div class="navbar navbar-bottom" id="footer"><h4 style="margin-left:1200px; color:white">Bratislav Miletic 2015.</h4></div>
	

</body>
</html>

app/views/notifier/order_received.html.erb
<h3>Poštovani <%= @order.name %></h3>

<p> Uspešno ste poručili proizvode preko www.bacva.rs.
Vaša porudžbina sadrži sledeće proizvode:</p>
<table>
	<tr>
	<td><%= render @order.line_items %></td>
	</tr>

	<tr>
	<td>Ukupan iznos:</td>
	<td><%= @order.total_price %></td> 
	</tr>

</table>

<p> Naknadno ćete biti obavešteni putem email-a o isporuci porudžbine.</p>

app/views/notifier/order_received.text.erb
Poštovani <%= @order.name %>

Uspešno ste poručili proizvode preko www.bacva.rs.
Vaša porudžbina sadrži sledeće proizvode:

<%= render @order.line_items %>
Naknadno ćete biti obavešteni putem email-a o isporuci porudžbine.

test TEXT

app/views/notifier/order_shipped.html.erb
<h1>Notifier#order_shipped</h1>

<p>
  <%= @greeting %>, find me in app/views/notifier/order_shipped.html.erb
</p>

app/views/notifier/order_shipped.text.erb
Notifier#order_shipped

<%= @greeting %>, find me in app/views/notifier/order_shipped.text.erb